### ISSUE TITLE
How to customize validation message from Form Request ?

### ISSUE THREAD

**Issue by styvesamson** [laravel-validation-rules/credit-card#11]
<?php

namespace App\Shop\Checkout\Requests;

use App\Shop\Base\BaseFormRequest;
use LVR\CreditCard\CardCvc;
use LVR\CreditCard\CardNumber;
use LVR\CreditCard\CardExpirationDate;

class  CreditCardRequest extends BaseFormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {

        return [
            'number' => ['required', new CardNumber],
            'expiry' => ['required', new CardExpirationDate($this->get('expiry'))],
            'cvc' => ['required', new CardCvc($this->get('number'))],
            'parcelas' => 'required',
            'cpf' => 'required',
            'telefone' => 'required|max:15',
        ];
    }

    /**
     * Get the error messages for the defined validation rules.
     *
     * @return array
     */

    public function messages()

    {

        return [
            'number.credit_card.card_checksum_invalid' => 'your credit card number is invalid',

        ];

    }
}

**Comment by DarkaOnLine** [comment]
Just translate `validation.credit_card.card_checksum_invalid` like you like.

**Comment by zakir1929** [comment]
add this code into any of your service provider boot method

``` 
Validator::replacer('cs_captcha_validate', function($message, $attribute, $rule, $parameters) {
            return sprintf('Recaptcha Invalid', $attribute);
}); 
```
        
        here cs_captcha_validate is the input field
