### ISSUE TITLE
how to customise validation message?

### ISSUE THREAD

**Issue by mahesh4ilapz** [laravel-validation-rules/credit-card#23]

**Comment by DarkaOnLine** [comment]
You just can add a translation for your new message

**Comment by egorsmkv** [comment]
Maybe is it better to add translations to the package?

**Comment by henzel** [comment]
resources/lang/{YOUR_LANGUAGE}/validation.php
Just add this:

'credit_card' => [
        'card_invalid' => '1',
        'card_pattern_invalid' => '2',
        'card_length_invalid' => '3',
        'card_checksum_invalid' => '4',
        'card_expiration_year_invalid' => '5',
        'card_expiration_month_invalid' => '6',
        'card_expiration_date_invalid' => '7',
        'card_expiration_date_format_invalid' => '8',
        'card_cvc_invalid' => '9',
],

**Comment by zakir1929** [comment]
add this code into any of your service provider boot method

``` 
Validator::replacer('cs_captcha_validate', function($message, $attribute, $rule, $parameters) {
            return sprintf('Recaptcha Invalid', $attribute);
}); 
```
        
        here cs_captcha_validate is the input field
