### ISSUE TITLE
Add laravel 7 support

### ISSUE THREAD

**Issue by nnerijuss** [laravel-validation-rules/credit-card#31]
Add laravel 7 support to composer.json file

```json
{
    "require": {
        "illuminate/validation": "^5.5|^6.0|^7.0",
        "illuminate/translation": "^5.5|^6.0|^7.0"
    }
}
```

**Comment by ssx** [comment]
I’ll take a look at these later today to bring them up to Laravel 7.


From: Nerijus Stakutis <notifications@github.com> <notifications@github.com>
Reply: laravel-validation-rules/credit-card
<reply@reply.github.com>
<reply@reply.github.com>
Date: 8 March 2020 at 11:07:45
To: laravel-validation-rules/credit-card <credit-card@noreply.github.com>
<credit-card@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [laravel-validation-rules/credit-card] Add laravel 7 support
(#31)

Add laravel 7 support o composer.json file
