### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by moetanahy** [laravel-validation-rules/credit-card#40]
Hi,

I can see there's some work on making the library support PHP8, but I'm still getting errors when adding this library to my project.

 Root composer.json requires laravel-validation-rules/credit-card 1.5.0 -> satisfiable by laravel-validation-rules/credit-card[1.5.0].
    - laravel-validation-rules/credit-card 1.5.0 requires php 7.* -> your php version (8.0.1) does not satisfy that requirement.

Is there an expected timeline on when this will be updated?

**Comment by DarkaOnLine** [comment]
I just released a new version. Please use `1.6.0` - https://github.com/laravel-validation-rules/credit-card/releases/tag/1.6.0
