### ISSUE TITLE
Package is not working with Laravel 11

### ISSUE THREAD

**Issue by brainstormer786** [laravel-validation-rules/credit-card#56]
I am updating a website to Laravel 11 but this package is not working with that. Please provide Laravel 11 support ASAP.

**Comment by bianchi** [comment]
There is a PR open for that [PR](https://github.com/laravel-validation-rules/credit-card/pull/55). We just have to wait to be accepted.

**Comment by slavcodev** [comment]
This seems not actual, please close.
