### ISSUE TITLE
Typo in expiration year

### ISSUE THREAD

**Issue by blairwigley** [laravel-validation-rules/credit-card#7]
Error is validation.credit_card.card_expiation_year_invalid (expiration spelt wrong).

**Comment by blairwigley** [comment]
Just realised this has already been fixed - is the version on composer up to date?

**Comment by ssx** [comment]
Morning Blair, 

I’ll check whether auto update is set.

**Comment by ssx** [comment]
1.0.5 has the fix in it and is the latest on packagist.

**Comment by blairwigley** [comment]
Thanks for the quick reply - I've checked that I'm running 1.0.5 

`laravel-validation-rules/credit-card  1.0.5   Validate credit card number, expiration date, cvc`

But CardExpirationYear.php still has the typo on line 9:  

`const MSG_CARD_EXPIRATION_YEAR_INVALID = 'validation.credit_card.card_expiation_year_invalid';`

 Any ideas?

**Comment by ssx** [comment]
Hi @blairwigley, I'll take a proper look this evening.

**Comment by ssx** [comment]
Fixed in 2a6064eb24b3d5ba5dddc2d66a1b36d633c45b10
