### ISSUE TITLE
JCB card is not validate

### ISSUE THREAD

**Issue by cesarureno** [laravel-validation-rules/credit-card#8]
I'working with Stripe, i tested cards form here [Test card numbers](https://stripe.com/docs/testing#cards)

Only fail JCB card number, can you fix it?

**Comment by DarkaOnLine** [comment]
I just tested JCB card number and it passes validation

**Comment by cesarureno** [comment]
I got this message
<img width="535" alt="screen shot 2018-05-29 at 02 54 33" src="https://user-images.githubusercontent.com/1313729/40645319-a7761800-62eb-11e8-9e34-caa83ef38a0d.png">

**Comment by DarkaOnLine** [comment]
It's failing due to the spaces. Will release fix

**Comment by DarkaOnLine** [comment]
hmmm, I do not know if it's correct to trim all spaces before validation. Does stripe or other providers except credit card numbers with spaces?

**Comment by DarkaOnLine** [comment]
Its really strange, we even have this card number in our tests and it's passing: https://github.com/laravel-validation-rules/credit-card/blob/master/tests/Unit/Cards/JcbTest.php#L19

**Comment by cesarureno** [comment]
I have decided to eliminate the spaces before validating and everything works perfect, thank you very much
